
name: rule_engine

env: dev  # 环境 dev demo prod


input:
  kafka:
    enabled : true
    server : ["10.210.228.22:9092"]
    user : "producer"
    passwd : "producer"
    group_id: kafka_input_group_id


output:
  es:
    enabled : false
    es_host : ["http://10.210.228.22:9201", "http://10.210.228.52:9201"]
    version : 7
    user : "elastic"
    passwd : "es_passwd"

  kafka:
    enabled : false
    server : ["10.210.228.22:9092"]
    user : "user"
    passwd : "kafka_passwd"
    topic: test22
    group_id: output_1


  email:
    enabled: false
    email_host: smtp.qq.com
    email_smtp_port: 465
    email_from: 123456@qq.com
    email_username: 123456
    email_pwd: 123456


  json:
    enabled : true
    path : /Users/njcx/RuleCat/logs/
    name : alert.log






